-- Core collection tables.
--
-- These were previously created by Hibernate's ddl-auto=update in development and had to exist
-- already in production (ddl-auto=none) — a fresh production database simply had no schema.
--
-- Every statement is idempotent so this migration is a no-op against the databases that were
-- built by ddl-auto. Combined with baseline-on-migrate that gives one code path for a fresh
-- database and for one with months of history in it.

CREATE TABLE IF NOT EXISTS trip (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    train_code  varchar(255),
    train_date  varchar(255),
    train_type  varchar(255),
    origin      varchar(255),
    destination varchar(255),
    direction   varchar(255)
);

CREATE TABLE IF NOT EXISTS trip_station_snapshot (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id           bigint  NOT NULL,
    station_code      varchar(255),
    station_full_name varchar(255),
    service_scope     varchar(255),
    sch_depart        varchar(255),
    sch_arrival       varchar(255),
    exp_depart        varchar(255),
    exp_arrival       varchar(255),
    late_minutes      integer NOT NULL,
    status            varchar(255),
    captured_at       timestamp(6)
);

-- Hibernate named these with a generated hash (ukqrytm7pxi9idmi8x47kfw54js,
-- fk6ryju3i3obe6uv44dbnblf2uy). Match on the columns rather than the name so an existing database
-- keeps the constraint it already has instead of gaining a duplicate under a new name.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        WHERE t.relname = 'trip'
          AND c.contype = 'u'
          AND c.conkey @> ARRAY[
                (SELECT attnum FROM pg_attribute WHERE attrelid = t.oid AND attname = 'train_code'),
                (SELECT attnum FROM pg_attribute WHERE attrelid = t.oid AND attname = 'train_date')]
    ) THEN
        ALTER TABLE trip ADD CONSTRAINT uk_trip_train_code_train_date UNIQUE (train_code, train_date);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        WHERE t.relname = 'trip_station_snapshot'
          AND c.contype = 'f'
    ) THEN
        ALTER TABLE trip_station_snapshot
            ADD CONSTRAINT fk_tss_trip FOREIGN KEY (trip_id) REFERENCES trip (id);
    END IF;
END $$;
